### ISSUE TITLE
Renaming Interplanetary Idea System (IPIS)

### ISSUE THREAD

**Issue by himalayajung** [open-science-org/OIPs#4]
In a recent reddit post on IPIS https://www.reddit.com/r/Open_Science/comments/8pbg4m/discussion_on_interplanetary_idea_system_ipis/, a reddit user suggested renaming IPIS to something better. After some contemplation, I see his/her point. 

I propose following options:
1) Interplanetary Idea System (IPIS) [no change]
2) Interplanetary Knowledge System (IPKS)
3) Generalized Idea System (GIS)
4) Generalized Idea Protocol (GIP)
5) Generalized Idea Model (GIM)
6) Idea Model
7) Idea Protocol
8) Other options

Please let us know your suggestions.

**Comment by oso-network** [comment]
We decided to change it to Generalized Idea Protocol (GIP)
